### ISSUE TITLE
👁️ 디자인 디테일

### ISSUE THREAD

**Issue by ryjmn** [DeveloperAcademy-POSTECH/MacC-Team2-Nutty#115]
## 📍 UT 전까지 반영할 디테일
- 모든 디자인 디테일 목록 中 **오류🚨**는 개발 공수가 적게 든다면 최대한 픽스 부탁드립니다
- UT 전까지 반영할 디테일 목록 中 **개발 공수가 적게 드는 것부터** 픽스 부탁드립니다. 다 반영하면 좋지만 그러기는 쉽지 않을 것 같다는 점 감안할게여

**PatientInfoView**
|개발된 모습|디자인 시안 (이대로 해주세여)|
|---|---|
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/219e0024-9bf3-4f3d-b2a3-6a908fec1aa4" width=180>|<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/9e38faf0-12f4-4cd5-9633-60fbf98ed80f" width=180>
- 텍스트필드_오류🚨
- [x] 입력 시 텍스트필드의 하이트 값이 커졌다 작아졌다하는 오류 수정(꿈틀꿈틀뷰) 
// ##help 도저히 모르겠어요 도와주세요 -에렌
- 알러트
- [x] 고정 _(지금은 스크롤 시 같이 따라 올라 감)_ // 에렌 (~11/6) -> 수정하면 애니메이션이 부자연스러워져요. 보여주러 제가 찾아갈게요
- [x] 패딩: 하단 16px _(지금은 패딩 값이 너무 작음)_ // 에렌 (~11/6) -> 원래 20이였는데 28로 수정
- [x] SF 심볼: 보라색 → Green4
- 텍스트필드_패딩
- [x] 모든 텍스트필드 입력 후 다시 어르신 성함 수정할 경우_패딩: 하단 60px _(지금은 패딩 값이 작아 CTA 버튼에 가려서 안 보임)_ // 에렌 (~11/6)

**IDCardConfirmEditView**
|개발된 모습|디자인 시안 (이대로 해주세여)|
|---|---|
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/99ecd2c8-74b2-40c4-be47-1836eb972901" width=180>|<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/3bbf5201-29a2-4ceb-b5bc-b82cd85ba75d" width=180>
- 타이틀
- [x] 고정 _(지금은 스크롤 시 같이 따라 올라 감)_
- 알러트
- [x] 고정 _(지금은 스크롤 시 같이 따라 올라 감)_
- [x] Width: 다른 알러트 Width와 맞추기 _(지금은 조금 넓음)_
- [x] 패딩: 하단 16px _(지금은 패딩 값이 너무 작음)_
- [x] SF 심볼: 보라색 → Green4
- 사진
- [x] 패딩: 좌우 패딩 0px
- 사진-텍스트필드_패딩
- [x] 조금 넓게 _(지금은 좁음)_
- 텍스트필드
- [x] 스트로크_색상: Green4 _(지금은 색상이 연함)_
- [x] 패딩: 하단 60px _(지금은 패딩 값이 작아 CTA 버튼과 간격이 좁음)_
- CTA 버튼
- [x] 하단에 고정 _(지금은 키패드와 같이 따라 올라옴)_
- 키패드 완료 버튼 → 주소 API 키보드와 통일
- [x] 오른쪽 정렬
- [x] 블러 제거

 ## 🫠 모든 디자인 디테일 목록
**OnboardingView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/1518e3c0-7bae-42b9-90a0-7cbe4f0a964a" width=180>
- 타이틀
- [x] 띄어쓰기: 요양보호사,복지용구 → 요양보호사, 복지용구 // 에렌 (~11/6)

**ApplyTypeView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/0809dbe6-0c6c-4168-b10a-dd5c769b7545" width=180> <img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/4f2bae1d-6c32-4d94-8b9c-883c4956b8ea" width=180>
- 라디오버튼
 - [x] 설명 텍스트_컬러: B → G5 // 에렌 (~11/6)
 - [x] Selected일 때, 스트로크_코너 래디우스: 10 _(지금은 값이 더 크게 설정돼있어서 연두색 영역이 삐져나와 보임)_ // 에렌 (~11/6)

**PrivacyPolicyView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/eccef821-7368-4f0a-9eeb-3032c6a16e67" width=180>
- 딤
- [x] 컬러: #000000 30% _(지금은 너무 진함)_ // 에렌 (~11/6)

**StepView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/96e04d07-9e92-47b1-898b-f42251f5f37e" width=180>
- 원문자-스트로크_패딩
- [x] 스트로크 상하 패딩 값 통일 _(지금은 상단 패딩이 더 좁고 하단 패딩이 더 큼)_ // 에렌 (~11/6)

**MediConditionView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/bd67eca9-ed75-4527-aa33-dc80ca7b5eb2" width=180>
- 라디오버튼_텍스트
- [x] 아니오 → 아니요로 문구 수정 // 에렌 (~11/6)

**AddressFormView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/a16c6a15-822e-4194-98a9-5e52883f3a3d" width=180> <img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/4438e7b3-220c-464d-992a-705a7cc34c35" width=180>
- 알러트
- [x] SF 심볼: 보라색 → Green4
- [x] 텍스트: 이야기해요 → 의미해요
- 텍스트필드
- [x] Width: 다른 필드 Width와 맞추기 _(지금은 조금 넓음)_

**ActualAddressCheckView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/1cab3e74-52eb-43f9-9a57-3b8e9dfb2442" width=180>
- 딤
- [x] 컬러: #000000 30% _(지금은 너무 진함)_
- CTA 버튼
- [x] 마진: 좌우마진이 다른 CTA버튼에 비해 넓음 → 다른 CTA 버튼과 마진 통일
- 텍스트 마침표 삭제
- [x] 설명텍스트 : 추가 입력이 필요해요. → 추가 입력이 필요해요

**AgentInfoView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/9d50e537-2741-4f64-b2b2-5aecb9e654bf" width=180>
- 텍스트 언더 스트로크
- [x] 굵기: 1pt(지금은 굵음) // 에렌(~11/6)
- [x] 색상: G5 → G4 // 에렌(~11/6)

**AgentInfoDetailView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/cd0191b5-cc4a-4e0f-aec9-88fe7d3dc98a" width=180>
- 백버튼_오류🚨
- [x] 백버튼 클릭 시 두번 뒤로가지는(StepView로 이동하는) 오류 발생 // 에렌 (~11/6)

**IDCardDescrptionView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/16dd7dbb-ba63-4de7-84a4-f308a8632930" width=180>
- 텍스트
- [x] 타이틀: 있도록 → 있게 
- [x] 설명: 온점 제거

**IDCardOCRView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/bc621c9f-a59f-4eb6-ac96-684cdae7332c" width=180> <img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/05c1552d-d7ef-46c6-9f35-899dd454db31" width=180>
- 텍스트박스
- [x] 패딩: 상하패딩 조금 더 넓게(지금은 살짝 찌부된 느낌)
- 딤
- [x] 컬러: #000000 60%(지금은 너무 연함)
- CTA 버튼
- [x] 마진: 좌우마진이 다른 CTA버튼에 비해 좁음 → 다른 CTA 버튼과 마진 통일
- 모달_패딩
- [x] 상단 패딩: 넓게 (지금은 조금 좁음)
- 텍스트
- [x] 색상: G6 → G5

**SignatureView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/5281e602-d4e3-4ceb-8ccb-3538790a784d" width=180>
- 알러트
- [x] SF 심볼: 보라색 → Green4
- 사인필드_오류🚨
- [x] 사인이 사인필드 밖으로 삐져나오는 경우 O

**SubmitCheckListView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/d5045922-f2ee-4a61-9ec1-dcf8852ece8a" width=180>
- 텍스트
- [x] 대리인 → 실제 사용자 이름 (ex: 김유진)
- [x] 패딩: 좌우 패딩이 조금 좁음 → CTA 버튼과 맞출 것
- 체크박스_오류🚨
- [x] 체크박스 해제가 안 되는 오류 O

**Comment by JJunghyunY** [comment]
1. Camera관련 뷰( IDCardConfirmEditView, IDCardDescrptionView, IDCardOCRView)
2. Address관련 뷰(AddressFormView, ActualAddressCheckView)
적용했습니다.

추가로 Alert의 SF Symbol은 asset으로 적용되어있어서 asset 변경했습니다

**Comment by mun9769** [comment]
@JJunghyunY `SubmitCheckListView` 제가 작업해도 괜찮나요? 컴포넌트 만들어서 뷰 작업을 다시 할 계획이에요

**Comment by ge-um** [comment]
@mun9769 제가 손대고 있긴 한데 디자인 디테일이 아니라 수정할 수 있도록 만드는거라 그냥 고치시면 될 것 같아요~

**Comment by mun9769** [comment]
남은 일은 #127로 옮기고 해당 이슈는 닫아준다
