### ISSUE TITLE
Edit Details 1105

### ISSUE THREAD

**Issue by mun9769** [DeveloperAcademy-POSTECH/MacC-Team2-Nutty#119]
## 📝 To-do

## 추가된 내용
- [x] underline 1px 내리기
- [x] selected button의 stroke 투명도 70퍼 & 내용 텍스트 색상 Green4로 변경
- [x] 꿈틀꿈틀 이슈, 텍스트 필드의 높이를 텍스트의 높이에 따라 동적으로 계산해줘서 생긴 이슈. 텍스트필드의 높이를 고정시켜서 해결해줌.

<details close>
<summary> 11/6 전 내용 </summary>

|개발된 모습|디자인 시안 (이대로 해주세여)|
|---|---|
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/219e0024-9bf3-4f3d-b2a3-6a908fec1aa4" width=180>|<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/9e38faf0-12f4-4cd5-9633-60fbf98ed80f" width=180>
**PatientInfoView**
- 텍스트필드_오류🚨
- [x] 입력 시 텍스트필드의 하이트 값이 커졌다 작아졌다하는 오류 수정(꿈틀꿈틀뷰) 
- 알러트
- [x] 고정 _(지금은 스크롤 시 같이 따라 올라 감)_ // 에렌 (~11/6) -> 애니메이션이 다소 부자연스러워지지만 알러트를 고정시킨다
- [x] 패딩: 하단 16px _(지금은 패딩 값이 너무 작음)_ // 에렌 (~11/6) -> 원래 20이였는데 28로 수정
- [x] SF 심볼: 보라색 → Green4
- 텍스트필드_패딩
- [x] 모든 텍스트필드 입력 후 다시 어르신 성함 수정할 경우_패딩: 하단 60px _(지금은 패딩 값이 작아 CTA 버튼에 가려서 안 보임)_ // 에렌 (~11/6)

**OnboardingView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/1518e3c0-7bae-42b9-90a0-7cbe4f0a964a" width=180>
- 타이틀
- [x] 띄어쓰기: 요양보호사,복지용구 → 요양보호사, 복지용구 // 에렌 (~11/6)

**ApplyTypeView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/0809dbe6-0c6c-4168-b10a-dd5c769b7545" width=180> <img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/4f2bae1d-6c32-4d94-8b9c-883c4956b8ea" width=180>
- 라디오버튼
 - [x] 설명 텍스트_컬러: B → G5 // 에렌 (~11/6)
 - [x] Selected일 때, 스트로크_코너 래디우스: 10 _(지금은 값이 더 크게 설정돼있어서 연두색 영역이 삐져나와 보임)_ // 에렌 (~11/6)

**PrivacyPolicyView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/eccef821-7368-4f0a-9eeb-3032c6a16e67" width=180>
- 딤
- [x] 컬러: #000000 30% _(지금은 너무 진함)_ // 에렌 (~11/6)

**StepView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/96e04d07-9e92-47b1-898b-f42251f5f37e" width=180>
- 원문자-스트로크_패딩
- [x] 스트로크 상하 패딩 값 통일 _(지금은 상단 패딩이 더 좁고 하단 패딩이 더 큼)_ // 에렌 (~11/6)

**MediConditionView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/bd67eca9-ed75-4527-aa33-dc80ca7b5eb2" width=180>
- 라디오버튼_텍스트
- [x] 아니오 → 아니요로 문구 수정 // 에렌 (~11/6)

**AgentInfoDetailView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/cd0191b5-cc4a-4e0f-aec9-88fe7d3dc98a" width=180>
- 백버튼_오류🚨
- [x] 백버튼 클릭 시 두번 뒤로가지는(StepView로 이동하는) 오류 발생 // 에렌 (~11/6)

**AgentInfoView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/9d50e537-2741-4f64-b2b2-5aecb9e654bf" width=180>
- 텍스트 언더 스트로크
- [x] 굵기: 1pt(지금은 굵음) // 에렌(~11/6)
- [x] 색상: G5 → G4 // 에렌(~11/6)

</details>
