### ISSUE TITLE
edit details

### ISSUE THREAD

**Issue by mun9769** [DeveloperAcademy-POSTECH/MacC-Team2-Nutty#145]
## 📝 To-do
- [x] 텍스트필드 아웃라인 회색으로 변경
- [ ] confirmeditview와 addressview 버튼 높이가 다름
- [ ] 전화번호 없어요 버튼이랑 align 맞추기 + 버튼 svg 불러오기
- [ ] 전화번호 11글자 다 입력될 때 유효성 검증
- [ ] 없어요 클릭 시 non focused되게
- [ ] UserDefault에 HomeViewState 저장하기
