### ISSUE TITLE
Modify Design Details

### ISSUE THREAD

**Issue by mun9769** [DeveloperAcademy-POSTECH/MacC-Team2-Nutty#56]
## 📝 To-do
 - [x] PatientInfoView:
     - [x]  키보드 내려간 상태에선 둥근 버튼으로 변경 
     - [x] 키보드의 return과 다음 버튼이 텍스트필드 포커싱을 이동시키기
     - [x] 텍스트필드 옆쪽 짤림 이슈 해결하기
 - [x] MediConditionView
     - [x] ~~"아니요" 일때 다음 플로우 이동, "네"가 있다면 RejectView~~  
아니요/아니요 면 거절화면이 나와야하는줄 알았는데 스마일시니어는 상관없네?

<details>
<summary> PatientInfoView </summary> 

<img src=https://user-images.githubusercontent.com/59304977/273677915-e10def8a-6d03-43a9-b46c-0eeb51e76f28.gif width=220>

</details>

<details>
<summary> MediConditionView </summary> 

<img src=https://user-images.githubusercontent.com/59304977/274070575-753762e9-d5ea-40ed-b705-359acb68c477.png width=220>

</details>
