### ISSUE TITLE
Create OnboardingView / Modify MainView and PatientInfoView

### ISSUE THREAD

**Issue by mun9769** [DeveloperAcademy-POSTECH/MacC-Team2-Nutty#77]
## 📝 To-do

patientinfoView
 - [x] 라벨과 입력필드 간 패딩 10 -> 8
 - [x] 전부 입력 후 다음 버튼 활성화
 - [x] 오토포커싱으로 빼기
 - [x] alert 창 자연스럽게 보여주기
 - [x] Alert, Button 컴포넌트로 교체하기

MainView
 - [x] tabbar 수정
 - [ ] 타이틀 수정

 OnboardingView 
 - [x] 온보딩 뷰 만들기 

기타
 - [x] 네비게이션 애니메이션 없애기
